"""create related book junction table

Revision ID: b2c3d4e5f6a1
Revises: a1b2c3d4e5f6
Create Date: 2026-07-10 18:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6a1'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookrelation')
    op.create_table(
        'relatedbook',
        sa.Column('book_a_id', sa.Integer(), nullable=False),
        sa.Column('book_b_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['book_a_id'], ['book.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['book_b_id'], ['book.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('book_a_id', 'book_b_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatedbook')
    op.create_table(
        'bookrelation',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('book_id', sa.Integer(), sa.ForeignKey('book.id')),
        sa.Column('related_book_ids', sa.ARRAY(sa.Integer()))
    )
    # ### end Alembic commands ###
